# Generated by Django 4.2.16 on 2024-12-20 16:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_suitabilitytest_vectortest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhanaBuiltSettlement',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('filename', models.TextField()),
            ],
            options={
                'db_table': 'ghanabs',
                'managed': False,
            },
        ),
    ]
