# Generated by Django 4.2.10 on 2024-02-22 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_alter_vectortest_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vectortest',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 24, 20, 21, 28, 320554, tzinfo=datetime.timezone.utc)),
        ),
    ]
