# Generated by Django 4.2.1 on 2023-07-21 22:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Map", "0003_ghanammda_delete_ghanadistricts"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Gh260Mmda",
        ),
    ]
