# Generated by Django 4.2.10 on 2024-02-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0003_alter_vectortest_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vectortest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vectortest',
            name='expiry_date',
        ),
    ]
