# Generated by Django 4.2.9 on 2024-02-13 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0004_delete_gh260mmda'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2024, 2, 15, 19, 32, 6, 718591, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
