# Generated by Django 4.2.10 on 2024-03-23 22:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0004_remove_vectortest_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitabilityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.FloatField()),
                ('road_suit', models.FloatField()),
                ('pop', models.FloatField()),
                ('pop_suit', models.FloatField()),
                ('urb', models.FloatField()),
                ('urb_suit', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
