# Generated by Django 4.2.10 on 2024-02-13 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0005_geodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 19, 39, 25, 504809, tzinfo=datetime.timezone.utc)),
        ),
    ]
