# Generated by Django 4.2.10 on 2024-02-13 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0007_alter_geodata_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 15, 19, 46, 50, 224100, tzinfo=datetime.timezone.utc)),
        ),
    ]
