# Generated by Django 4.2.10 on 2024-02-13 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0009_alter_geodata_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJSONData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2024, 2, 13, 20, 16, 20, 865748, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.DeleteModel(
            name='GeoData',
        ),
    ]
