# Generated by Django 4.2.10 on 2024-02-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0010_geojsondata_delete_geodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojsondata',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
