# Generated by Django 4.2.10 on 2024-02-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0012_geodata_delete_geojsondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJSONData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='GeoData',
        ),
    ]
