# Generated by Django 4.2.16 on 2024-09-13 16:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0014_suitabilitytest_vectortest_delete_geojsondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhanaMGRS',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('mgrs', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
            ],
            options={
                'db_table': 'ghanamgrs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GhanaPopDens',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('rast', django.contrib.gis.db.models.fields.RasterField(srid=4326)),
                ('filename', models.TextField()),
            ],
            options={
                'db_table': 'ghanapopdens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GhanaRoads',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('fclass', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=3857)),
            ],
            options={
                'db_table': 'ghanaroads',
                'managed': False,
            },
        ),
    ]
