# Generated by Django 4.2.16 on 2024-09-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0015_ghanamgrs_ghanapopdens_ghanaroads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ghanammda',
            options={'managed': False},
        ),
    ]
