# Generated by Django 4.2.16 on 2024-09-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0016_alter_ghanammda_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ghanammda',
            table='ghanammda',
        ),
    ]
